title: 5hubh4m
email: shubhamchaudhary1996@gmail.com
description: Home
baseurl: ""
url: "https://5hubh4m.github.io"
twitter_username: postmodernKatze
github_username:  5hubh4m
theme: no-style-please
exclude:
- LICENSE
- README.md
- build.sh
- Gemfile*
theme_config:
  appearance: auto
  back_home_text: ..
goat_counter: 5hubh4m
whitelist:
- jekyll-seo-tag