title: shubham chaudhary
email: shubhamchaudhary1996@gmail.com
description: >-
  Hey, there. This is Shubham Chaudhary, and this is
  a website about me and my work.
baseurl: ""
url: "https://5hubh4m.github.io"
twitter_username: postmodernKatze
github_username:  5hubh4m
theme: no-style-please
exclude:
- LICENSE
- README.md
- build.sh
- Gemfile*
theme_config:
  appearance: auto
  back_home_text: home
goat_counter: 5hubh4m
whitelist:
- jekyll-seo-tag